name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    outputs:
      salida: Todo esta bien por aqui
    
    steps:
      - name: Generar archivo
        run: |
          echo "Archivo prueba, hola" >> test.log
      
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: test.log
          path: test.log

      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: test.log 