name: "Hola mundo"

on:
  push:
    branches: ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hacemos pull del codigo"
      - run: echo "Corremos migraciones"
      - run: echo "Reiniciamos el servidor"
      - run: echo "Deploy finalizado"
